openapi: 3.0.0
info:
  title: API Simples
  description: Exemplo básico de Swagger
  version: 1.0.0

servers:
  - url: http://localhost:3333/users
    description: Servidor local

paths:
  /usuarios:
    get:
      summary: Retorna lista de usuários
      responses:
        '200':
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              example:
                - id: 1
                  nome: João
                - id: 2
                  nome: Maria

  /usuarios/{id}:
    get:
      summary: Retorna um usuário específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              example:
                id: 1
                nome: João
                email: joao@exemplo.com
        '404':
          description: Usuário não encontrado